### ISSUE TITLE
Support for Space along with Enter key in itemListener?

### ISSUE THREAD

**Issue by prios-chris-abbato** [sparksuite/react-accessible-dropdown-menu-hook#269]
Hi there, is there any reason that Space was not supported in keyboard accessibility similar to Enter? Is this something you are considering adding?

Thanks!

**Comment by corymharper** [comment]
Hi @prios-chris-abbato thanks for opening the issue and asking! The keyboard controls we implemented were based on this list of keyboard interactions: https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-12. At the time of implementation we decided to only implement those keyboard controls marks as "Required" for the initial release. I am not at all opposed to implementing other keyboard controls described in that documentation, we will definitely consider adding it.

**Comment by corymharper** [comment]
We will probably get to this pretty quickly, but if you would like to see a change like this more immediately and have the time, I definitely encourage you to [make a contribution](https://github.com/sparksuite/react-accessible-dropdown-menu-hook/blob/master/CONTRIBUTING.md)!
