### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by pke** [sparksuite/react-accessible-dropdown-menu-hook#294]
I wonder if this could be easily extended to support react native?

**Comment by corymharper** [comment]
I'm not personally familiar with React Native to much extent, a quick overview of their [accessibility](https://reactnative.dev/docs/accessibility) documentation seems to reveal that there are a lot of similar ideas, and probably that a lot of the same ideas could be taken from this package to create something fairly familiar, but the implementation would be significantly different enough that I believe it would be better placed in another package.

**Comment by pke** [comment]
Thanks for the evaluation! Sounds like a nice side project then :)
