### ISSUE TITLE
Usage of deprecated method

### ISSUE THREAD

**Issue by ShahriarKh** [sparksuite/react-accessible-dropdown-menu-hook#299]
Warning in Firefox:
```
Element.setCapture() is deprecated. Use Element.setPointerCapture() instead.  
For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture

[touch-simulator.js:219:19]
```

**Comment by corymharper** [comment]
@ShahriarKh are you sure this is coming from this package? A look at the [source code](https://github.com/sparksuite/react-accessible-dropdown-menu-hook/blob/master/src/use-dropdown-menu.ts) doesn't have any usage of that method. Its possible that the code is being transpiled in such a way that it includes that method, but I wouldn't be sure of why immediately.

**Comment by ShahriarKh** [comment]
I will take a look again. Maybe an extension is throwing this warning. However, I only see it in "Seeing Theory".
