### ISSUE TITLE
Hovering over "Get started" button hides text

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/react-accessible-dropdown-menu-hook#305]
When hovering over the "Get started" button, the text disappears:

![GIF Recording 2022-12-16 at 4 51 44 PM](https://user-images.githubusercontent.com/3850064/208201669-218e8531-a279-488c-98e7-4d60d99100f7.gif)

**Comment by corymharper** [comment]
See https://github.com/sparksuite/w3c-css-validator/issues/145#issuecomment-1409249077 for an explanation about what's happening, its the same problem.
