### ISSUE TITLE
Rework focus on click behavior

### ISSUE THREAD

**Issue by corymharper** [sparksuite/react-accessible-dropdown-menu-hook#312]
Currently, by default the behavior of the hook is to focus  the first item when the menu is opened, regardless of how it was opened. It is not specified by the WAI Aria guidelines that this has to be the case on click, but it should be on keyboard interaction. Therefore we should change the default behavior of the hook to be to focus the first item of the menu when it is opened via keyboard interaction, but not when it is opened via click.

At the same time we will create a new option, `focusFirstItemOnClick` that will invert that behavior for clicking.

**Comment by WesCossick** [comment]
> Therefore we should change the default behavior of the hook to be to focus the first item of the menu when it is opened via keyboard interaction, but when it is opened via click.

Can you clarify this sentence? I'm not sure it's complete.

**Comment by WesCossick** [comment]
I've marked this as an enhancement rather than a refactor since it's improving and changing the behavior of the package, rather than simply reorganizing/restructuring the code for readability/maintainability/etc. reasons.

**Comment by corymharper** [comment]
> > Therefore we should change the default behavior of the hook to be to focus the first item of the menu when it is opened via keyboard interaction, but when it is opened via click.
> 
> Can you clarify this sentence? I'm not sure it's complete.

Oh, there was supposed to be a "not" in there, fixed it!

**Comment by chrisxcooper** [comment]
> Therefore we should change the default behavior of the hook to be to focus the first item of the menu when it is opened via keyboard interaction, but not when it is opened via click.

Hey, I'm a user of this package so firstly thank you for continuing to add enhancements. I'm currently overriding `moveFocus` being set to the first item as I want it on the selected item (defaulted to first).

As such, I wondered where the focus will be based on the proposed change when opened via click? Will it be on the selected item (defaulted to first) or could this be controllable to save the manual override?

**Comment by corymharper** [comment]
> > Therefore we should change the default behavior of the hook to be to focus on the first item of the menu when it is opened via keyboard interaction, but not when it is opened via click.
> 
> Hey, I'm a user of this package so firstly thank you for continuing to add enhancements. I'm currently overriding `moveFocus` being set to the first item as I want it on the selected item (defaulted to first).
> 
> As such, I wondered where the focus will be based on the proposed change when opened via click? Will it be on the selected item (defaulted to first) or could this be controllable to save the manual override?

This issue was resolved in #313 and those changes are available in version `4.0.0`. These changes made it so that on click focus would not shift to one of the menu items, it would remain on the menu button, the button that opens the menu.
