### ISSUE TITLE
Demo website tweaks

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/react-accessible-dropdown-menu-hook#58]
- [ ] Add a favicon
- [ ] Make all links in the footer open in a new tab

**Comment by idiglove** [comment]
I love your library, its so simple
Can I work on this ticket?

**Comment by WesCossick** [comment]
Looks like this is an outdated issue; the above improvements would have applied to the old demo website before we modernized the website in https://github.com/sparksuite/react-accessible-dropdown-menu-hook/pull/251.
