### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/react-accessible-dropdown-menu-hook#7]
Add in the tests and ensure they run properly with `npm test`. Tests should be contained within the `test/` folder, and should be suffixed with `.test.ts` to work.

Enzyme and Puppeteer are available for use in tests, which are run by Jest.

**Comment by corymharper** [comment]
For testing with puppeteer, I believe we will have to implement a simple component that runs on https://localhost:3000/ or something similar. An example using create-react-app can be found at [this](https://github.com/smooth-code/jest-puppeteer/tree/master/examples/create-react-app) repo, and some further guides I found on the issue were here:

[LogRocket](https://blog.logrocket.com/end-to-end-testing-react-apps-with-puppeteer-and-jest-ce2f414b4fd7/)
[Bits and Pieces](https://blog.bitsrc.io/testing-your-react-app-with-puppeteer-and-jest-c72b3dfcde59)
[Better Programming](https://medium.com/better-programming/simple-react-app-testing-with-puppeteer-979fe882fb80)

**Comment by WesCossick** [comment]
I believe the best solution for this is to wait to add Puppeteer tests until we’ve created the demo site using Create React App. Then we can run the demo website locally, and run Puppeteer tests against that demo site.

**Comment by corymharper** [comment]
For enzyme to function correctly we will also need jsdom as a dependency, should it be added, or not do tests with enzyme?

**Comment by WesCossick** [comment]
> For enzyme to function correctly we will also need jsdom as a dependency, should it be added, or not do tests with enzyme?

Can you point to documentation that shows when and why JSDOM is required for Enzyme?

**Comment by corymharper** [comment]
> > For enzyme to function correctly we will also need jsdom as a dependency, should it be added, or not do tests with enzyme?
> 
> Can you point to documentation that shows when and why JSDOM is required for Enzyme?

https://airbnb.io/enzyme/docs/guides/jsdom.html

> Since enzyme's mount API requires a DOM, JSDOM is required in order to use mount if you are not already in a browser environment (ie, a Node environment).

**Comment by WesCossick** [comment]
The docs read:
> if you are not already in a browser environment (ie, a Node environment).

Jest should run the tests with Node.js.

**Comment by corymharper** [comment]
Currently all of the test suites fail with this error:

```
It looks like you called `mount()` without a global document being loaded.
```

I'm unsure of a way to effectively mock the browser document without using jsdom.

**Comment by WesCossick** [comment]
That's odd; this is the example project that the official Enzyme docs link to: https://github.com/vjwilson/enzyme-example-jest. It doesn't use JSDOM... I'm not really sure what's going on.

**Comment by WesCossick** [comment]
Can you push the branch you're working on to GitHub so that I can inspect the code?
