### ISSUE TITLE
Make the menu close when an item is clicked

### ISSUE THREAD

**Issue by corymharper** [sparksuite/react-accessible-dropdown-menu-hook#70]
Currently the hook only manages closing and opening the menu element when keyboard controls are being utilized. This leaves it up to the developer to implement closing and opening their menu element when an item is clicked. This is suboptimal because they can not properly utilize the `isOpen` boolean value returned by the hook if the developer(s) must rely on a different value for click events.

Due to this some solution needs to be implemented to detect item clicks and close the menu in response.

**Comment by corymharper** [comment]
One solution that comes to mind is adding an `onClick` event listener to each item through it's ref. This would avoid interfering with the `onClick` handler the dev creates in React. It would mean having two separate onClick listeners for each item in the list, however.

**Comment by WesCossick** [comment]
As a note, the reason this Hook does not automatically close the menu when an item is clicked, but does when an item is activated with the keyboard, is because that's how the specs suggest designing dropdown menus. So if we design it to close automatically via clicks, this would be a slight deviation from the WAI-ARIA guidelines.

**Comment by WesCossick** [comment]
> One solution that comes to mind is adding an `onClick` event listener to each item through it's ref. This would avoid interfering with the `onClick` handler the dev creates in React. It would mean having two separate onClick listeners for each item in the list, however.

This would not adhere to standard React principles, so we should not do this.

**Comment by corymharper** [comment]
> > One solution that comes to mind is adding an `onClick` event listener to each item through it's ref. This would avoid interfering with the `onClick` handler the dev creates in React. It would mean having two separate onClick listeners for each item in the list, however.
> 
> This would not adhere to standard React principles, so we should not do this.

I will have to think about a different approach. I had a solution that looked something like this:

```
itemRefs.current?.forEach(ref => ref.current?.addEventListener('click', () => setIsOpen(false)))
```

in a `useEffect` that was already implemented. Any ideas about how else to detect the clicks on each item? When implementing the hook the dev does not currently pass the hook any information about what they want the items to do, that is left up to them. Without that I haven't thought of a very React friendly way to implement an onClick.

**Comment by WesCossick** [comment]
Hmmm, that is sort of tricky... Maybe do some research to see if there are going to be any unintended consequences of adding a click listener directly via the DOM element, and not via React.

**Comment by corymharper** [comment]
It seems like it's the correct practice at least for implementing event listeners that React has not yet implemented. For performance reasons the biggest concern would be adding too many event listeners this way since we are manually adding them and removing them. But as long as that is being managed correctly I haven't read about any unintended consequences from imperatively adding the listeners, it just is an anti-pattern to reacts declarative style I think.

**Comment by corymharper** [comment]
While researching and looking at our code I did have some concerns about this useEffect on line [52](https://github.com/sparksuite/react-accessible-dropdown-menu-hook/blob/master/src/use-dropdown-menu.ts#L52), unless I am interpreting it incorrectly, isn't this currently adding a click event listener every time isOpen changes, until the component dismounts?

**Comment by WesCossick** [comment]
> It seems like it's the correct practice at least for implementing event listeners that React has not yet implemented. For performance reasons the biggest concern would be adding too many event listeners this way since we are manually adding them and removing them. But as long as that is being managed correctly I haven't read about any unintended consequences from imperatively adding the listeners, it just is an anti-pattern to reacts declarative style I think.

Okay, then maybe that's the route we'll take to solve this issue.

**Comment by WesCossick** [comment]
> While researching and looking at our code I did have some concerns about this useEffect on line [52](https://github.com/sparksuite/react-accessible-dropdown-menu-hook/blob/master/src/use-dropdown-menu.ts#L52), unless I am interpreting it incorrectly, isn't this currently adding a click event listener every time isOpen changes, until the component dismounts?

Maybe, you can investigate that and open a separate issue if you think there's a bug.
